services:
  - type: web
    name: mintyshirt-frontend
    env: node
    buildCommand: yarn install && yarn run build
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000

  - type: web
    name: mintyshirt-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend/src && python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: <secure secret>
      - key: DATABASE_URL
        value: <database url>
