name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'index.html'
      - 'package.json'
      - 'vite.config.ts'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'index.html'
      - 'package.json'
      - 'vite.config.ts'
      - 'tsconfig.json'
      - 'tsconfig.node.json'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      continue-on-error: true

    - name: Build
      run: npm run build
        
    - name: Trigger Netlify deploy
      if: success( ) && github.ref == 'refs/heads/main'
      run: |
        curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
